name: Artifact

on: [push]

env:
   ARTIFACT_NAME: myartifact

job:
  main: 
    runs-on: ubuntu-latest
    steps:
     -name: check out the code
      use: actions/checkout@v2
     -name: upload the artifacts  
      use: actions/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: .
       
